### ISSUE TITLE
Who is the Guide audience (Public vs. Member)

### ISSUE THREAD

**Issue by svgeesus** [w3c/Guide#121]
Noticed today during strat discussions:

The guide [states](https://www.w3.org/Guide/)

> This page is Public

which is good, and useful, and should to the extent possible be true.

The first non-navigation section then states

> Note: The information in this section is W3C Member-only.

which is sad, confusing, and off-putting. Also partly untrue. The information, the titles, are clearly public. What is not public are the links, which go to the Member-only chairs mailing list archive.

I am concerned that readers may not go on to the following sections in the guide, after such an unwelcoming and confusing message.

There are several things that might fix this. 

**Firstly**, the list of newsworthy links, which does have value, could be moved to another page to clearly separate out the Member-only from the Public information.

**Secondly**, is the information really Member-only? For example

> 2020 Process Document and Patent Policy operational

That isn't Member only. Both documents, [W3C Process Document](https://www.w3.org/2020/Process-20200915/) & [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20200915/)  are public. The only Member part is that the announcement was made to a Member-only list.

> Changes to I18N HR requests

Again, public. The [GitHub repo for I18N HR requests](https://github.com/w3c/i18n-request/) is public. The only Member part is that the announcement was made to a Member-only list.

> Automatic publications - Chairs can now create tokens

That one, token creation, is indeed restricted to Chairs only. 

> Feedback on Horizontal Review

That is a request for feedback, including from document editors. Unfortunately, any document editor who doesn't have Member access won't have seen that request; the announcement was made to a Member-only list.

So there is a pattern of creating news items from selected, archived  postings to a Member-only list. This could be made more welcoming by also posting the public ones to some public list and linking to that archive, to make the news items.

**Thirdly**, re-examine whether the Chairs list needs to be public or whether a new, Public, Chairs list could be used for most postings?

**Comment by swickr** [comment]
You raise several interesting points, @svgeesus,  The question raised by the phrasing of the issue title is perhaps one of the simpler of them.

IMHO the Guide is to guide current and future participants in how W3C does its work.  The _audience_ is therefore those who need to -- or wish to -- know details that aren't described by our formal documents (Process, PP, Group Charters, CEPC, etc.)  This set is certainly larger than Members and Member Representatives.

A second question is how much, (and if not all then which) of the content warrants being blocked from public visibility.  Here the discussion might be better considered as "how does it benefit W3C to restrict access?" I suspect that a considerable portion of the content that is not currently visible to the world is restricted due to ease of implementation and 'accidents of history' rather than conscious decisions about specific cases.  So, for example, it's trivial to link to emails in the Chairs mailing list but it takes much more effort to consistently maintain two ways to communicate with the Chairs Audience; one that is world visible and one that receives (the occasional) email that is appropriately not quite public information (at least, not yet; e.g. because a press release is planned.)

Still, you raise some specific examples of things that may have legitimately been non-public at one time but our thinking has evolved and the material now ought to be public -- or maybe is already public and the nearby text in the Guide hasn't been updated.  To the extent that potential participants are discouraged from exploring the Guide, such out-of-date annotations of visibility can be harmful, I agree.   I suggest that updating such annotations falls within the expected and never-ending maintenance and curation of the Guide.  Whether it should be a priority to devote more resources to deeper curation of Guide, copy-editing public versions of previously internal-only announcements, or making more parallel communications channels is a more challenging issue.

**Comment by samuelweiler** [comment]
Ideally, a change log should point to parts of the (public) document that changed.  If we haven't updated the document, is this really just a punchlist of issues that we need to work into the document (and should probably be filed as issues here)?

I suggest prioritizing initial cleanup, if we can't point to sections within the Guide, then let's create github issues for the punchlist and remove the section that looks like a change log.
